apiVersion: v1
kind: Service
metadata:
  name: testnewcreds
  namespace: namespace-workflow-1724874248611
  labels:
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app: testnewcreds
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000